package adapter

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/shopspring/decimal"
	"github.com/yourusername/actus-go/pkg/actus/events"
	"github.com/yourusername/actus-go/pkg/codegen"
	"github.com/yourusername/actus-go/pkg/codegen/solidity"

	"github.com/smpebble/actus-fvm/internal/model"
)

// CodegenClient wraps the actus-go Solidity code generator.
type CodegenClient struct {
	generator  *solidity.Generator
	scriptsDir string
}

// NewCodegenClient creates a new code generation client.
func NewCodegenClient(baseDir string) *CodegenClient {
	return &CodegenClient{
		generator:  solidity.NewGenerator(),
		scriptsDir: filepath.Join(baseDir, "scripts"),
	}
}

// GenerateSolidityContract generates a Solidity smart contract from ACTUS contract parameters.
func (c *CodegenClient) GenerateSolidityContract(
	contractName string,
	actusType string,
	schedule events.EventSchedule,
	outputDir string,
) ([]model.GeneratedFile, error) {
	ir := codegen.NewContractIR(contractName, actusType)

	ir.Metadata.Description = fmt.Sprintf("ACTUS %s Financial Contract - Generated by FinanceVM", actusType)
	ir.Metadata.Author = "FinanceVM Code Generator"
	ir.Metadata.Version = "1.0.0"
	ir.Metadata.License = "MIT"

	// Add state variables
	ir.AddStateVariable(codegen.StateVariable{
		Name: "notionalPrincipal", Type: codegen.DataType{BaseType: "uint256"},
		Visibility: codegen.VisibilityPublic, Description: "Notional principal amount",
	})
	ir.AddStateVariable(codegen.StateVariable{
		Name: "nominalInterestRate", Type: codegen.DataType{BaseType: "uint256"},
		Visibility: codegen.VisibilityPublic, Description: "Nominal interest rate (basis points)",
	})
	ir.AddStateVariable(codegen.StateVariable{
		Name: "currency", Type: codegen.DataType{BaseType: "string"},
		Visibility: codegen.VisibilityPublic, Description: "Currency code",
	})
	ir.AddStateVariable(codegen.StateVariable{
		Name: "contractState", Type: codegen.DataType{BaseType: "uint8"},
		Visibility: codegen.VisibilityPublic, Description: "Current contract state",
	})
	ir.AddStateVariable(codegen.StateVariable{
		Name: "owner", Type: codegen.DataType{BaseType: "address"},
		Visibility: codegen.VisibilityPublic, Description: "Contract owner",
	})

	// Add events from schedule
	for _, event := range schedule {
		if !event.Payoff.Equal(decimal.Zero) {
			ir.Spec.ScheduledEvents = append(ir.Spec.ScheduledEvents, codegen.ScheduledEvent{
				EventType:   string(event.Type),
				ScheduledAt: event.Time,
				Payoff:      event.Payoff,
				Currency:    event.Currency,
			})
		}
	}

	// Add contract events
	ir.AddEvent(codegen.Event{
		Name:        "ContractInitialized",
		Description: "Emitted when contract is initialized",
		Parameters: []codegen.EventParameter{
			{Name: "owner", Type: codegen.DataType{BaseType: "address"}, Indexed: true},
			{Name: "notionalPrincipal", Type: codegen.DataType{BaseType: "uint256"}},
		},
	})
	ir.AddEvent(codegen.Event{
		Name:        "PaymentProcessed",
		Description: "Emitted when a payment is processed",
		Parameters: []codegen.EventParameter{
			{Name: "eventType", Type: codegen.DataType{BaseType: "string"}},
			{Name: "amount", Type: codegen.DataType{BaseType: "uint256"}},
			{Name: "timestamp", Type: codegen.DataType{BaseType: "uint256"}},
		},
	})

	// Add functions
	ir.AddFunction(codegen.Function{
		Name:        "initialize",
		Type:        codegen.FunctionTypeNonPayable,
		Visibility:  codegen.VisibilityExternal,
		Description: "Initialize the contract",
		Parameters: []codegen.Parameter{
			{Name: "_notionalPrincipal", Type: codegen.DataType{BaseType: "uint256"}},
			{Name: "_interestRate", Type: codegen.DataType{BaseType: "uint256"}},
		},
	})
	ir.AddFunction(codegen.Function{
		Name:        "processEvent",
		Type:        codegen.FunctionTypeNonPayable,
		Visibility:  codegen.VisibilityExternal,
		Description: "Process a scheduled ACTUS event",
		Parameters: []codegen.Parameter{
			{Name: "_eventType", Type: codegen.DataType{BaseType: "string"}},
			{Name: "_amount", Type: codegen.DataType{BaseType: "uint256"}},
		},
	})
	ir.AddFunction(codegen.Function{
		Name:        "getState",
		Type:        codegen.FunctionTypeView,
		Visibility:  codegen.VisibilityExternal,
		Description: "Get current contract state",
		Returns: []codegen.Parameter{
			{Name: "principal", Type: codegen.DataType{BaseType: "uint256"}},
			{Name: "rate", Type: codegen.DataType{BaseType: "uint256"}},
			{Name: "state", Type: codegen.DataType{BaseType: "uint8"}},
		},
	})

	opts := codegen.GeneratorOptions{
		Target:       codegen.LanguageSolidity,
		ContractName: contractName,
		IncludeTests: true,
		Version:      "0.8.20",
	}

	generated, err := c.generator.Generate(context.Background(), ir, opts)
	if err != nil {
		return nil, fmt.Errorf("solidity generation failed: %w", err)
	}

	var files []model.GeneratedFile

	// Write main contract file
	mainPath := filepath.Join(outputDir, generated.MainFile.Filename)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create output dir: %w", err)
	}
	if err := os.WriteFile(mainPath, []byte(generated.MainFile.Content), 0644); err != nil {
		return nil, fmt.Errorf("failed to write main contract: %w", err)
	}
	// Run compilation using local node script
	compileOut := ""
	cmd := exec.Command("node", "compile_solidity.js")
	cmd.Dir = c.scriptsDir
	cmd.Stdin = bytes.NewReader([]byte(generated.MainFile.Content))
	var outBytes bytes.Buffer
	cmd.Stdout = &outBytes
	if err := cmd.Run(); err == nil {
		compileOut = outBytes.String()
	} else {
		compileOut = fmt.Sprintf(`{"success":false,"errors":["%s"]}`, err.Error())
	}

	files = append(files, model.GeneratedFile{
		Filename:       generated.MainFile.Filename,
		Content:        generated.MainFile.Content,
		FileType:       string(generated.MainFile.FileType),
		CompilerOutput: compileOut,
	})

	// Write additional files
	for _, f := range generated.AdditionalFiles {
		fPath := filepath.Join(outputDir, f.Filename)
		if err := os.WriteFile(fPath, []byte(f.Content), 0644); err != nil {
			return nil, fmt.Errorf("failed to write %s: %w", f.Filename, err)
		}
		files = append(files, model.GeneratedFile{
			Filename: f.Filename,
			Content:  f.Content,
			FileType: string(f.FileType),
		})
	}

	return files, nil
}
